import { DataTypeDefinition } from "./types";

// Using flag-icons node module for the flags
export const QuestionData: DataTypeDefinition = [
	{
		question: "Kabul is the capital of",
		imageQuestion: false,
		imageUrl: "",
		answer: 3,
		answerText: "Afghanistan",
		options: ["Eswatini", "Senegal", "Afghanistan", "Tajikistan"],
	},
	{
		question: "Which country does this flag belong to?",
		imageQuestion: true,
		imageUrl: "af",
		answer: 3,
		answerText: "Afghanistan",
		options: [
			"Poland",
			"Senegal",
			"Afghanistan",
			"Turks and Caicos Islands",
		],
	},
	{
		question: "Mariehamn is the capital of",
		imageQuestion: false,
		imageUrl: "",
		answer: 1,
		answerText: "Åland Islands",
		options: ["Åland Islands", "Andorra", "India", "Réunion"],
	},
	{
		question: "Which country does this flag belong to?",
		imageQuestion: true,
		imageUrl: "ax",
		answer: 1,
		answerText: "Åland Islands",
		options: ["Åland Islands", "Uruguay", "India", "Réunion"],
	},
	{
		question: "Saint John's is the capital of",
		imageQuestion: false,
		imageUrl: "",
		answer: 4,
		answerText: "Antigua and Barbuda",
		options: ["Ethiopia", "Iceland", "Comoros", "Antigua and Barbuda"],
	},
	{
		question: "Which country does this flag belong to?",
		imageQuestion: true,
		imageUrl: "ag",
		answer: 4,
		answerText: "Antigua and Barbuda",
		options: [
			"Wallis and Futuna",
			"Åland Islands",
			"Comoros",
			"Antigua and Barbuda",
		],
	},
	{
		question: "Brussels is the capital of",
		imageQuestion: false,
		imageUrl: "",
		answer: 3,
		answerText: "Belgium",
		options: ["Bahamas", "Bulgaria", "Belgium", "Nicaragua"],
	},
	{
		question: "Which country does this flag belong to?",
		imageQuestion: true,
		imageUrl: "be",
		answer: 4,
		answerText: "Belgium",
		options: ["Bahamas", "Cyprus", "Mongolia", "Belgium"],
	},
	{
		question: "Gaborone is the capital of",
		imageQuestion: false,
		imageUrl: "",
		answer: 1,
		answerText: "Botswana",
		options: ["Botswana", "Eritrea", "Angola", "Albania"],
	},
	{
		question: "Which country does this flag belong to?",
		imageQuestion: true,
		imageUrl: "bw",
		answer: 2,
		answerText: "Botswana",
		options: [
			"Poland",
			"Botswana",
			"Angola",
			"Central African Republic (the)",
		],
	},
	{
		question: "Yaoundé is the capital of",
		imageQuestion: false,
		imageUrl: "",
		answer: 2,
		answerText: "Cameroun",
		options: ["Papua New Guinea", "Cameroun", "Brazil", "Japan"],
	},
	{
		question: "Which country does this flag belong to?",
		imageQuestion: true,
		imageUrl: "cm",
		answer: 1,
		answerText: "Cameroun",
		options: ["Cameroun", "Brazil", "Japan", "Mongolia"],
	},
	{
		question: "Buenos Aires is the capital of",
		imageQuestion: false,
		imageUrl: "",
		answer: 1,
		answerText: "Argentina",
		options: ["Argentina", "Sierra Leone", "Czechia", "French Polynesia"],
	},
	{
		question: "Which country does this flag belong to?",
		imageQuestion: true,
		imageUrl: "ar",
		answer: 4,
		answerText: "Argentina",
		options: ["Angola", "Mozambique", "Burundi", "Argentina"],
	},
	{
		question: "Madrid is the capital of",
		imageQuestion: false,
		imageUrl: "",
		answer: 4,
		answerText: "Spain",
		options: [
			"Guinea",
			"Lao People's Democratic Republic",
			"Canada",
			"Spain",
		],
	},
	{
		question: "Which country does this flag belong to?",
		imageQuestion: true,
		imageUrl: "es",
		answer: 1,
		answerText: "Spain",
		options: ["Spain", "Pakistan", "Burkina Faso", "Korea"],
	},
	{
		question: "Gitega is the capital of",
		imageQuestion: false,
		imageUrl: "",
		answer: 2,
		answerText: "Burundi",
		options: ["Burkina Faso", "Burundi", "Jordan", "Qatar"],
	},
	{
		question: "Which country does this flag belong to?",
		imageQuestion: true,
		imageUrl: "bi",
		answer: 3,
		answerText: "Burundi",
		options: ["South Sudan", "Zambia", "Burundi", "Aruba"],
	},
	{
		question: "Nicosia is the capital of",
		imageQuestion: false,
		imageUrl: "",
		answer: 4,
		answerText: "Cyprus",
		options: ["Liechtenstein", "Namibia", "Hungary", "Cyprus"],
	},
	{
		question: "Which country does this flag belong to?",
		imageQuestion: true,
		imageUrl: "cy",
		answer: 1,
		answerText: "Cyprus",
		options: ["Cyprus", "Netherlands", "Senegal", "Israel"],
	},
	{
		question: "Maseru is the capital of",
		imageQuestion: false,
		imageUrl: "",
		answer: 1,
		answerText: "Lesotho",
		options: ["Lesotho", "Seychelles", "Sierra Leone", "Algeria"],
	},
	{
		question: "Which country does this flag belong to?",
		imageQuestion: true,
		imageUrl: "ls",
		answer: 4,
		answerText: "Lesotho",
		options: ["American Samoa", "Turkmenistan", "China", "Lesotho"],
	},
	{
		question: "Chisinau is the capital of",
		imageQuestion: false,
		imageUrl: "",
		answer: 3,
		answerText: "Moldova",
		options: ["Marshall Islands (the)", "Togo", "Moldova", "Pakistan"],
	},
	{
		question: "Which country does this flag belong to?",
		imageQuestion: true,
		imageUrl: "md",
		answer: 2,
		answerText: "Moldova",
		options: ["Albania", "Moldova", "Virgin Islands (British)", "Libya"],
	},
	{
		question: "Abuja is the capital of",
		imageQuestion: false,
		imageUrl: "",
		answer: 2,
		answerText: "Nigeria",
		options: ["Indonesia", "Nigeria", "Turks and Caicos Islands", "Gambia"],
	},
	{
		question: "Which country does this flag belong to?",
		imageQuestion: true,
		imageUrl: "ng",
		answer: 4,
		answerText: "Nigeria",
		options: ["Grenada", "Guadeloupe", "Pakistan", "Nigeria"],
	},
	{
		question: "Berlin is the capital of",
		imageQuestion: false,
		imageUrl: "",
		answer: 2,
		answerText: "Germany",
		options: [
			"Luxembourg",
			"Germany",
			"Northern Mariana Islands (the)",
			"Togo",
		],
	},
	{
		question: "Which country does this flag belong to?",
		imageQuestion: true,
		imageUrl: "de",
		answer: 1,
		answerText: "Germany",
		options: ["Germany", "Pakistan", "Burkina Faso", "Korea"],
	},
	{
		question: "Cairo is the capital of",
		imageQuestion: false,
		imageUrl: "",
		answer: 3,
		answerText: "Egypt",
		options: [
			"Uganda",
			"Bonaire, Sint Eustatius and Saba",
			"Egypt",
			"Cameroon",
		],
	},
	{
		question: "Which country does this flag belong to?",
		imageQuestion: true,
		imageUrl: "eg",
		answer: 4,
		answerText: "Egypt",
		options: ["Germany", "Bosnia and Herzegovina", "Iraq", "Egypt"],
	},
	{
		question: "Paris is the capital of",
		imageQuestion: false,
		imageUrl: "",
		answer: 1,
		answerText: "France",
		options: ["France", "Belarus", "Tanzania", "Russia"],
	},
	{
		question: "Which country does this flag belong to?",
		imageQuestion: true,
		imageUrl: "fr",
		answer: 2,
		answerText: "France",
		options: ["Germany", "France", "Iraq", "Egypt"],
	},
	{
		question: "Bissau is the capital of",
		imageQuestion: false,
		imageUrl: "",
		answer: 3,
		answerText: "Guinea-Bissau",
		options: ["Nigeria", "Mauritius", "Guinea-Bissau", "Kuwait"],
	},
	{
		question: "Which country does this flag belong to?",
		imageQuestion: true,
		imageUrl: "gw",
		answer: 2,
		answerText: "Guinea-Bissau",
		options: ["Serbia", "Guinea-Bissau", "Turkmenistan", "Gabon"],
	},
	{
		question: "Tokyo is the capital of",
		imageQuestion: false,
		imageUrl: "",
		answer: 1,
		answerText: "Japan",
		options: ["Japan", "Kazakhstan", "Palau", "Chad"],
	},
	{
		question: "Which country does this flag belong to?",
		imageQuestion: true,
		imageUrl: "jp",
		answer: 4,
		answerText: "Japan",
		options: ["Burundi", "Japan", "Mali", "Guinea-Bissau"],
	},
	{
		question: "Bogota is the capital of",
		imageQuestion: false,
		imageUrl: "",
		answer: 3,
		answerText: "Colombia",
		options: ["Comoros", "Mali", "Colombia", "Côte d'Ivoire"],
	},
	{
		question: "Which country does this flag belong to?",
		imageQuestion: true,
		imageUrl: "co",
		answer: 1,
		answerText: "Colombia",
		options: ["Colombia", "Japan", "Panama", "Yemen"],
	},
	{
		question: "Zagreb is the capital of",
		imageQuestion: false,
		imageUrl: "",
		answer: 4,
		answerText: "Croatia",
		options: ["Mexico", "Somalia", "Russia", "Croatia"],
	},
	{
		question: "Which country does this flag belong to?",
		imageQuestion: true,
		imageUrl: "hr",
		answer: 1,
		answerText: "Croatia",
		options: ["Croatia", "Tuvalu", "Eswatini", "Yemen"],
	},
	{
		question: "Kingston is the capital of",
		imageQuestion: false,
		imageUrl: "",
		answer: 2,
		answerText: "Jamaica",
		options: ["Thailand", "Jamaica", "Cabo Verde", "Norway"],
	},
	{
		question: "Which country does this flag belong to?",
		imageQuestion: true,
		imageUrl: "jm",
		answer: 4,
		answerText: "Jamaica",
		options: ["Croatia", "Tuvalu", "Sierra Leone", "Jamaica"],
	},
];
